version: '3'

services:

  prod:
    image: whatanime-backend-prod
    build:
      context: .
      dockerfile: ./Dockerfile-prod
    environment:
      PORT: ${PORT}
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - sonic
    networks:
      - backend

  sonic:
    image: 'valeriansaliou/sonic:v1.3.2'
    container_name: sonic
    restart: always
    volumes:
      - ./.docker/sonic/config.cfg:/etc/sonic.cfg
      - ./.docker/sonic/store/:/var/lib/sonic/store/
    networks:
      - backend

networks:
  backend:
    driver: bridge
