version: '3'

services:

  app:
    build: ./bff
    container_name: app
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - "3333:3333"
    volumes:
      - "./bff:/home/node/app"
    networks:
      - whatanime
    depends_on:
      - sonic
      - mongo

  sonic:
    image: valeriansaliou/sonic:v1.3.2
    container_name: sonic
    restart: always
    volumes:
      - ./sonic/config.cfg:/etc/sonic.cfg
      - ./sonic/store/:/var/lib/sonic/store/
    ports:
      - "1491:1491"
    networks:
      - whatanime

  db:
    image: mongo:5.0.5
    container_name: mongo
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
      - ./.docker/mongo:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    networks:
      - whatanime
    environment:
      - MONGO_INITDB_DATABASE=whatanime
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - whatanime
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root

networks:
  whatanime:
    driver: bridge
