version: '3'

services:

  app:
    build: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://mongo:27017 -timeout 30s node dist/main.js
    ports:
      - "5000:5000"
    volumes:
      - "./node:/home/node/app"
    networks:
      - whatanime
    depends_on:
      - db
      - sonic
      - redis
    environment:
      - MONGO_DSN=${MONGO_DSN}

  sonic:
    image: valeriansaliou/sonic:v1.3.2
    container_name: sonic
    restart: always
    volumes:
      - ./sonic/config.cfg:/etc/sonic.cfg
      - ./sonic/store/:/var/lib/sonic/store/
    networks:
      - whatanime

  db:
    image: mongo:4.4.11
    container_name: mongo
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
    ports:
      - 27017:27017
    networks:
      - whatanime

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - whatanime    

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - whatanime

networks:
  whatanime:
    driver: bridge
