version: '3'

services:

  app:
    build: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://sonic:1491 -timeout 30s ./entrypoint.sh
    ports:
      - "3333:3333"
    volumes:
      - "./node:/home/node/app"
    networks:
      - network-whatanime
    depends_on:
      - sonic
      - redis
    environment:
      MONGO_DSN: ${MONGO_DSN}

  sonic:
    image: valeriansaliou/sonic:v1.3.2
    container_name: sonic
    restart: always
    volumes:
      - ./sonic/config.cfg:/etc/sonic.cfg
      - ./sonic/store/:/var/lib/sonic/store/
    networks:
      - network-whatanime

  redis:
    image: redis:6.2.6
    container_name: redis
    restart: always
    networks:
      - network-whatanime

networks:
  network-whatanime:
    driver: bridge
