version: '3'

services:

  app:
    build: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://mongo:27017 -timeout 30s ./entrypoint.sh
    ports:
      - "3333:3333"
    volumes:
      - "./node:/home/node/app"
    networks:
      - network-whatanime
    depends_on:
      - sonic
      - db

  sonic:
    image: valeriansaliou/sonic:v1.3.2
    container_name: sonic
    restart: always
    volumes:
      - ./sonic/config.cfg:/etc/sonic.cfg
      - ./sonic/store/:/var/lib/sonic/store/
    ports:
      - "1491:1491"
    networks:
      - network-whatanime

  db:
    image: mongo:5.0.5
    container_name: mongo
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
    ports:
      - 27017:27017
    networks:
      - network-whatanime

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - network-whatanime

networks:
  network-whatanime:
    driver: bridge
