version: '3'

services:

  dev:
    image: whatanime-backend-dev
    container_name: whatanime-backend-dev
    build:
      context: .
      target: builder
      dockerfile: ./Dockerfile
    command: dockerize -wait tcp://database:5432 -timeout 30s npm run start:dev
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - sonic
      - redis
    restart: unless-stopped
    networks:
      - backend

  sonic:
    image: 'valeriansaliou/sonic:v1.3.2'
    container_name: sonic
    restart: always
    ports:
      - '1491:1491'
    volumes:
      - ./.docker/sonic/config.cfg:/etc/sonic.cfg
      - ./.docker/sonic/store/:/var/lib/sonic/store/
    networks:
      - backend

  database:
    image: 'bitnami/postgresql'
    container_name: database
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=app
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - backend

volumes:
  postgresql_data:
    driver: local

networks:
  backend:
    driver: bridge
