name: ci-sonarcloud
on:
  pull_request:
    branches:
      - dev

jobs:
  run-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.x", "17.x"]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npx --no-install lint-staged
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
